Support sentiment analysis in multiple languages
CatalystCode/botbuilder-instrumentation pull request #13
Opened 2017-07-09 17:49 UTC by iMicknl

At the moment the sentiment analysis is supported in [15 languages ](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/overview), but `botbuilder-instrumentation` uses English as hardcoded default. 

In think that the right way should be to retrieve the preferredLocale since this should be used to set the language for the current session. However, maybe there should be a setting to override the behaviour via the settings to add a default language?

Only the first two characters are taken from the preferredLocale since the sentiment analysis API only accepts the country code without culture code. (en vs en-us)

2017-07-10 15:24 UTC, iMicknl commented
If anyone has suggestions how to make sure we only query supported languages, let me know. A hardcoded array inside the source doesn't have my preference, but maybe I should add the possibility to pass an array of supported languages via the options?

2017-07-11 15:19 UTC, morsh commented
@iMicknl - I'm guessing one way to go about it, is enable an array of supported languages.
If this is supplied you can pass each phrase through language recognizer service and that result (in case in the array) can be passed to the sentiment analysis service

2017-07-11 15:53 UTC, iMicknl commented
@morsh thanks! Performance wise, I don't think the 'Language Detection' API should be enabled by default, since it is an extra API request. If a chatbot uses multiple languages there is a big chance they are already using an API like this. Using session.preferredLocale() by default is the best option in my opinion, with the option to enable the 'Language Detection' via the options.

The 'Language Detection API' is also not very accurate while detecting smaller sentences, however this doesn't matter that much is the result is just used for sentiments analysis. 

I will work something out and update this pull request!

2017-07-20 10:36 UTC, morsh requested changes

2017-07-20 10:36 UTC, morsh commented on dist/main.js
> +                        "language": session.preferredLocale().substring(0, 2) || "en",
@iMicknl - thanks for the update, just please make sure there are no nulls/undefined with:
session; session.preferredLocale()
(Here and below)

2018-10-01 16:29 UTC, iMicknl commented
Sorry, forgot about this and will close it since v4 is already out of preview at the moment.

2018-10-01 16:29 UTC, closed without merging